./" this is the manpage of the pamix pulseaudio ncurses mixer
.TH pamix 1 "14.08.2016" "V1.2" "pamix man page"

.SH SYONPSIS
pamix

.SH DESCRIPTION
This is a pavucontrol inspired ncurses based pulseaudio mixer for the commandline

.SH KEY BINDINGS
F1      show Playback tab
        
F2      show Recording tab
        
F3      show Output devices tab
        
F4      show Input devices tab
        
j/J     select next channel/entry
        
k/K     select previous channel/entry
        
h/l     decrease/increase volume
        
c       un/lock channels
        
s/S     select next/previous device/port
